### ISSUE TITLE
Preview of additional images doesnt work anymore

### ISSUE THREAD

**Issue by CarlosDeSantoz** [yfszzx/stable-diffusion-webui-inspiration#13]
great extension !

those additional images on the lower right side, after you click an artist, doesnt work anymore since the last update of stable diffusion.

Would be nice if this could get fixed.

Best...

**Comment by CarlosDeSantoz** [comment]
Also, all the buttons "to txt2img" etc. dont work anymore for me... (everything was fine before last update of SD)

**Comment by yfszzx** [comment]
done
