### ISSUE TITLE
(Ettore "Ted" DeGrazia) all works well starts to populate, until this issue occurs when it reaches the same name each time 

### ISSUE THREAD

**Issue by TWIISTED-STUDIOS** [yfszzx/stable-diffusion-webui-inspiration#15]
all works well starts to populate, until this issue occurs when it reaches the same name each time

`Error completing request[3:37:46,  5.28it/s]
Arguments: ('', '', 'None', 'None', 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 0, 0, 7, 0.9, 5, '0.0001', False, 'None', '', 0.1, False, 1, 0, 0.25, False, False, False, None, '', False, 4.0, '', 10.0, False, False, True, 30.0, True, False, False, 0, 0.0, 1, '', 0, '', True, False, False, '<div id="dynamic-prompting">\n    <h3><strong>Combinations</strong></h3>\n\n    Choose a number of terms from a list, in this case we choose two artists: \n    <code class="codeblock">{{2$artist1|artist2|artist3}}</code>\n\n    If $ is not provided, then 1$ is assumed.\n\n    A range can be provided:\n    <code class="codeblock">{{1-3$artist1|artist2|artist3}}</code>\n\n    In this case, a random number of artists between 1 and 3 is chosen.\n\n    <br/><br/>\n\n    <h3><strong>Wildcards</strong></h3>\n    \n\n    <br/>\n    If the groups wont drop down click <strong onclick="check_collapsibles()" style="cursor: pointer">here</strong> to fix the issue.\n\n    <br/><br/>\n\n    <code class="codeblock">WILDCARD_DIR: E:\\Artificial-Inteligence\\Ai-Image-Gen\\Automatic-1111-GUI\\stable-diffusion-webui\\extensions\\sd-dynamic-prompts\\wildcards</code><br/>\n    <small onload="check_collapsibles()">You can add more wildcards by creating a text file with one term per line and name is mywildcards.txt. Place it in E:\\Artificial-Inteligence\\Ai-Image-Gen\\Automatic-1111-GUI\\stable-diffusion-webui\\extensions\\sd-dynamic-prompts\\wildcards. <code class="codeblock">__&#60;folder&#62;/mywildcards__</code> will then become available.</small>\n</div>\n\n', False, 1, False, False, 4.0, 1.0, 'a painting in', 'style', 'picture frame, portrait photo', [<tempfile._TemporaryFileWrapper object at 0x000002338C6FE800>]) {}
Traceback (most recent call last):
  File "E:\Artificial-Inteligence\Ai-Image-Gen\Automatic-1111-GUI\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "E:\Artificial-Inteligence\Ai-Image-Gen\Automatic-1111-GUI\stable-diffusion-webui\webui.py", line 55, in f
    res = func(*args, **kwargs)
  File "E:\Artificial-Inteligence\Ai-Image-Gen\Automatic-1111-GUI\stable-diffusion-webui\modules\txt2img.py", line 45, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "E:\Artificial-Inteligence\Ai-Image-Gen\Automatic-1111-GUI\stable-diffusion-webui\modules\scripts.py", line 282, in run
    processed = script.run(p, *script_args)
  File "E:\Artificial-Inteligence\Ai-Image-Gen\Automatic-1111-GUI\stable-diffusion-webui\extensions\stable-diffusion-webui-inspiration\scripts\inspiration.py", line 52, in run
    os.mkdir(artist_path)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'E:\\Artificial-Inteligence\\Ai-Image-Gen\\Automatic-1111-GUI\\stable-diffusion-webui\\extensions\\stable-diffusion-webui-inspiration\\inspiration\\artists\\Ettore "Ted" DeGrazia`

**Comment by TWIISTED-STUDIOS** [comment]
![image](https://user-images.githubusercontent.com/20824886/199774919-755664bb-07c3-4fe7-a704-d70d2a3a8207.png)

**Comment by TWIISTED-STUDIOS** [comment]
Today the issue is gone, I haven't done anything that's changed just the issue is gone.

**Comment by chaosbunker** [comment]
I solved this problem by changing `Ettore "Ted" DeGrazia` to `Ettore 'Ted' DeGrazia` in artists.txt

**Comment by TWIISTED-STUDIOS** [comment]
> I solved this problem by changing `Ettore "Ted" DeGrazia` to `Ettore 'Ted' DeGrazia` in artists.txt

yh I noticed inside the flavour one also that there are many characters that can't be used and trailing spaces that can't be used either.
