### ISSUE TITLE
Downloaded images and placed images, I have a tab, but no updated UI

### ISSUE THREAD

**Issue by rethink-studios** [yfszzx/stable-diffusion-webui-inspiration#9]
Hey hey,
I've installed items here:

![image](https://user-images.githubusercontent.com/60104539/198403707-c368b4a2-ddbc-44ee-b684-b51a024f5fe3.png)

I have a tab, but not acknowledging assets 

![image](https://user-images.githubusercontent.com/60104539/198403855-89104ca3-0267-49d9-b725-a01870ca9a0d.png)

Any ideas?

Thanks in advance!

**Comment by yfszzx** [comment]
put artists and styles folds under “inspiration” fold
